#!/usr/bin/env python3
"""Generate _index.yaml from discovered catalog entries.

Scans evidence-analysis/Discovered/docs/catalog/*.yaml and produces
an aggregated _index.yaml matching the format used by ReferenceArchitectures.

Usage:
    python3 pipeline/generate-index.py
    python3 pipeline/generate-index.py --catalog-dir path/to/catalog --output path/to/_index.yaml
"""

import argparse
import os
import sys
from collections import Counter
from datetime import date

try:
    import yaml

    def load_yaml(path):
        with open(path) as f:
            return yaml.safe_load(f)

    def dump_yaml(data):
        return yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)

except ImportError:
    # Use the fallback parser from classify.py
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from classify import parse_yaml, dump_yaml

    def load_yaml(path):
        with open(path) as f:
            return parse_yaml(f.read())


def normalize_style_key(style):
    """Convert style name to kebab-case key for frequency map."""
    return style.lower().replace(" ", "-").replace("/", "-")


def generate_index(catalog_dir, output_path):
    """Scan catalog entries and produce _index.yaml."""
    entries = []
    style_counter = Counter()
    lang_counter = Counter()

    for fname in sorted(os.listdir(catalog_dir)):
        if not fname.endswith(".yaml") or fname.startswith("_"):
            continue

        path = os.path.join(catalog_dir, fname)
        try:
            entry = load_yaml(path)
        except Exception as e:
            print(f"Warning: failed to parse {fname}: {e}", file=sys.stderr)
            continue

        if not entry or not isinstance(entry, dict):
            continue

        styles = entry.get("architecture_styles", [])
        if not isinstance(styles, list):
            styles = []

        lang = entry.get("language", "Unknown")
        confidence = 0.0
        meta = entry.get("discovery_metadata", {})
        if isinstance(meta, dict):
            confidence = meta.get("confidence", 0.0)

        review = entry.get("review_required", False)
        status = "review-required" if review else "discovered"

        project = {
            "project_name": entry.get("project_name", fname.replace(".yaml", "")),
            "domain": entry.get("domain", "Unknown"),
            "language": lang,
            "architecture_styles": styles,
            "confidence": confidence,
            "status": status,
        }
        entries.append(project)

        for s in styles:
            style_counter[normalize_style_key(s)] += 1
        lang_counter[lang] += 1

    # Sort style frequency descending
    style_freq = dict(style_counter.most_common())
    lang_cov = dict(lang_counter.most_common())

    index = {
        "generated": str(date.today()),
        "source": "Discovered",
        "source_full_name": "Automated Architecture Discovery Pipeline",
        "evidence_type": "automated-discovery",
        "description": (
            "Architecture catalog entries produced by the SPEC-002 dataset scaling "
            "pipeline. Each entry is generated by running extract-signals.sh against "
            "a public GitHub repository and classifying the output using heuristic rules "
            "from signal-rules.md."
        ),
        "total_projects": len(entries),
        "projects": entries,
        "architecture_style_frequency": style_freq,
        "language_coverage": lang_cov,
    }

    output = dump_yaml(index)

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(output)

    print(f"Generated {output_path}: {len(entries)} projects")
    return index


def main():
    default_catalog = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..", "evidence-analysis", "Discovered", "docs", "catalog"
    )
    default_output = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..", "evidence-analysis", "Discovered", "_index.yaml"
    )

    parser = argparse.ArgumentParser(description="Generate _index.yaml from catalog entries")
    parser.add_argument("--catalog-dir", default=default_catalog,
                        help="Path to catalog directory with *.yaml entries")
    parser.add_argument("--output", default=default_output,
                        help="Output _index.yaml path")
    args = parser.parse_args()

    generate_index(args.catalog_dir, args.output)


if __name__ == "__main__":
    main()
